INIT_O_FILES :=\
	$(BUILD_DIR)/asm/init.o

EXTAB_O_FILES :=\
	$(BUILD_DIR)/asm/extab.o

EXTABINDEX_O_FILES :=\
	$(BUILD_DIR)/asm/extabindex.o

TEXT_O_FILES :=\
	$(BUILD_DIR)/asm/Core/x/iCamera.o\
	$(BUILD_DIR)/src/Core/x/iCamera.o\
	$(BUILD_DIR)/asm/Core/x/xAnim.o\
	$(BUILD_DIR)/src/Core/x/xAnim.o\
	$(BUILD_DIR)/asm/Core/x/xBallPhysics.o\
	$(BUILD_DIR)/src/Core/x/xBallPhysics.o\
	$(BUILD_DIR)/src/Core/x/xBase.o\
	$(BUILD_DIR)/src/Core/x/xBehaveGoalSimple.o\
	$(BUILD_DIR)/src/Core/x/xBehaveMgr.o\
	$(BUILD_DIR)/asm/Core/x/xbinio.o\
	$(BUILD_DIR)/src/Core/x/xbinio.o\
	$(BUILD_DIR)/src/Core/x/xBound.o\
	$(BUILD_DIR)/asm/Core/x/xCam.o\
	$(BUILD_DIR)/src/Core/x/xCam.o\
	$(BUILD_DIR)/src/Core/x/xCamFollow.o\
	$(BUILD_DIR)/asm/Core/x/xCamSupport.o\
	$(BUILD_DIR)/src/Core/x/xCamSupport.o\
	$(BUILD_DIR)/src/Core/x/xClimate.o\
	$(BUILD_DIR)/asm/Core/x/xClumpColl.o\
	$(BUILD_DIR)/src/Core/x/xClumpColl.o\
	$(BUILD_DIR)/asm/Core/x/xCM.o\
	$(BUILD_DIR)/src/Core/x/xCM.o\
	$(BUILD_DIR)/asm/Core/x/xCollide.o\
	$(BUILD_DIR)/src/Core/x/xCollide.o\
	$(BUILD_DIR)/src/Core/x/xCollideFast.o\
	$(BUILD_DIR)/src/Core/x/xColor.o\
	$(BUILD_DIR)/src/Core/x/xCounter.o\
	$(BUILD_DIR)/src/Core/x/xCurveAsset.o\
	$(BUILD_DIR)/asm/Core/x/xCutscene.o\
	$(BUILD_DIR)/src/Core/x/xCutscene.o\
	$(BUILD_DIR)/src/Core/x/xDebug.o\
	$(BUILD_DIR)/asm/Core/x/xDecal.o\
	$(BUILD_DIR)/src/Core/x/xDecal.o\
	$(BUILD_DIR)/asm/Core/x/xEnt.o\
	$(BUILD_DIR)/src/Core/x/xEnt.o\
	$(BUILD_DIR)/asm/Core/x/xEntBoulder.o\
	$(BUILD_DIR)/src/Core/x/xEntBoulder.o\
	$(BUILD_DIR)/asm/Core/x/xEntDrive.o\
	$(BUILD_DIR)/src/Core/x/xEntDrive.o\
	$(BUILD_DIR)/asm/Core/x/xEntMotion.o\
	$(BUILD_DIR)/src/Core/x/xEntMotion.o\
	$(BUILD_DIR)/src/Core/x/xEnv.o\
	$(BUILD_DIR)/src/Core/x/xEvent.o\
	$(BUILD_DIR)/src/Core/x/xFactory.o\
	$(BUILD_DIR)/asm/Core/x/xFFX.o\
	$(BUILD_DIR)/src/Core/x/xFFX.o\
	$(BUILD_DIR)/asm/Core/x/xFMV.o\
	$(BUILD_DIR)/src/Core/x/xFMV.o\
	$(BUILD_DIR)/src/Core/x/xFog.o\
	$(BUILD_DIR)/asm/Core/x/xFont.o\
	$(BUILD_DIR)/src/Core/x/xFont.o\
	$(BUILD_DIR)/asm/Core/x/xFX.o\
	$(BUILD_DIR)/src/Core/x/xFX.o\
	$(BUILD_DIR)/asm/Core/x/xGrid.o\
	$(BUILD_DIR)/src/Core/x/xGrid.o\
	$(BUILD_DIR)/src/Core/x/xGroup.o\
	$(BUILD_DIR)/src/Core/x/xHierarchyBound.o\
	$(BUILD_DIR)/src/Core/x/xhipio.o\
	$(BUILD_DIR)/asm/Core/x/xHud.o\
	$(BUILD_DIR)/src/Core/x/xHud.o\
	$(BUILD_DIR)/asm/Core/x/xHudFontMeter.o\
	$(BUILD_DIR)/src/Core/x/xHudFontMeter.o\
	$(BUILD_DIR)/asm/Core/x/xHudMeter.o\
	$(BUILD_DIR)/src/Core/x/xHudMeter.o\
	$(BUILD_DIR)/src/Core/x/xHudModel.o\
	$(BUILD_DIR)/asm/Core/x/xHudUnitMeter.o\
	$(BUILD_DIR)/src/Core/x/xHudUnitMeter.o\
	$(BUILD_DIR)/asm/Core/x/xIni.o\
	$(BUILD_DIR)/src/Core/x/xIni.o\
	$(BUILD_DIR)/src/Core/x/xJaw.o\
	$(BUILD_DIR)/asm/Core/x/xJSP.o\
	$(BUILD_DIR)/src/Core/x/xJSP.o\
	$(BUILD_DIR)/asm/Core/x/xLaserBolt.o\
	$(BUILD_DIR)/src/Core/x/xLaserBolt.o\
	$(BUILD_DIR)/src/Core/x/xLightKit.o\
	$(BUILD_DIR)/asm/Core/x/xMath.o\
	$(BUILD_DIR)/src/Core/x/xMath.o\
	$(BUILD_DIR)/src/Core/x/xMath2.o\
	$(BUILD_DIR)/asm/Core/x/xMath3.o\
	$(BUILD_DIR)/src/Core/x/xMath3.o\
	$(BUILD_DIR)/asm/Core/x/xMemMgr.o\
	$(BUILD_DIR)/src/Core/x/xMemMgr.o\
	$(BUILD_DIR)/asm/Core/x/xModel.o\
	$(BUILD_DIR)/src/Core/x/xModel.o\
	$(BUILD_DIR)/asm/Core/x/xModelBucket.o\
	$(BUILD_DIR)/src/Core/x/xModelBucket.o\
	$(BUILD_DIR)/asm/Core/x/xMorph.o\
	$(BUILD_DIR)/src/Core/x/xMorph.o\
	$(BUILD_DIR)/asm/Core/x/xMovePoint.o\
	$(BUILD_DIR)/src/Core/x/xMovePoint.o\
	$(BUILD_DIR)/asm/Core/x/xNavigationMeshAsset.o\
	$(BUILD_DIR)/src/Core/x/xNavigationMeshAsset.o\
	$(BUILD_DIR)/asm/Core/x/xOneLinerManager.o\
	$(BUILD_DIR)/src/Core/x/xOneLinerManager.o\
	$(BUILD_DIR)/asm/Core/x/xOneLinerPlayer.o\
	$(BUILD_DIR)/src/Core/x/xOneLinerPlayer.o\
	$(BUILD_DIR)/src/Core/x/xordarray.o\
	$(BUILD_DIR)/asm/Core/x/xPad.o\
	$(BUILD_DIR)/src/Core/x/xPad.o\
	$(BUILD_DIR)/src/Core/x/xParEmitter.o\
	$(BUILD_DIR)/src/Core/x/xParSys.o\
	$(BUILD_DIR)/asm/Core/x/xPartition.o\
	$(BUILD_DIR)/src/Core/x/xPartition.o\
	$(BUILD_DIR)/src/Core/x/xpkrsvc.o\
	$(BUILD_DIR)/asm/Core/x/xPtankPool.o\
	$(BUILD_DIR)/src/Core/x/xPtankPool.o\
	$(BUILD_DIR)/asm/Core/x/xQuickCull.o\
	$(BUILD_DIR)/src/Core/x/xQuickCull.o\
	$(BUILD_DIR)/asm/Core/x/xRand.o\
	$(BUILD_DIR)/src/Core/x/xRand.o\
	$(BUILD_DIR)/src/Core/x/xRegionSupport.o\
	$(BUILD_DIR)/src/Core/x/xRenderState.o\
	$(BUILD_DIR)/src/Core/x/xRMemData.o\
	$(BUILD_DIR)/asm/Core/x/xRumbleEmitter.o\
	$(BUILD_DIR)/src/Core/x/xRumbleEmitter.o\
	$(BUILD_DIR)/asm/Core/x/xRumbleManager.o\
	$(BUILD_DIR)/src/Core/x/xRumbleManager.o\
	$(BUILD_DIR)/asm/Core/x/xsavegame.o\
	$(BUILD_DIR)/src/Core/x/xsavegame.o\
	$(BUILD_DIR)/asm/Core/x/xScene.o\
	$(BUILD_DIR)/src/Core/x/xScene.o\
	$(BUILD_DIR)/asm/Core/x/xScreenWarp.o\
	$(BUILD_DIR)/src/Core/x/xScreenWarp.o\
	$(BUILD_DIR)/asm/Core/x/xScrFx.o\
	$(BUILD_DIR)/src/Core/x/xScrFx.o\
	$(BUILD_DIR)/src/Core/x/xserializer.o\
	$(BUILD_DIR)/asm/Core/x/xShadow.o\
	$(BUILD_DIR)/src/Core/x/xShadow.o\
	$(BUILD_DIR)/asm/Core/x/xShadowSimple.o\
	$(BUILD_DIR)/src/Core/x/xShadowSimple.o\
	$(BUILD_DIR)/asm/Core/x/xSkyDome.o\
	$(BUILD_DIR)/src/Core/x/xSkyDome.o\
	$(BUILD_DIR)/asm/Core/x/xSndMgr.o\
	$(BUILD_DIR)/src/Core/x/xSndMgr.o\
	$(BUILD_DIR)/src/Core/x/xSoundFX.o\
	$(BUILD_DIR)/asm/Core/x/xSpacePartitionTree.o\
	$(BUILD_DIR)/src/Core/x/xSpacePartitionTree.o\
	$(BUILD_DIR)/asm/Core/x/xSpline.o\
	$(BUILD_DIR)/src/Core/x/xSpline.o\
	$(BUILD_DIR)/asm/Core/x/xSplineAsset.o\
	$(BUILD_DIR)/src/Core/x/xSplineAsset.o\
	$(BUILD_DIR)/src/Core/x/xstransvc.o\
	$(BUILD_DIR)/asm/Core/x/xString.o\
	$(BUILD_DIR)/src/Core/x/xString.o\
	$(BUILD_DIR)/src/Core/x/xSubTitles.o\
	$(BUILD_DIR)/src/Core/x/xSurface.o\
	$(BUILD_DIR)/src/Core/x/xTextAsset.o\
	$(BUILD_DIR)/asm/Core/x/xTextureManager.o\
	$(BUILD_DIR)/src/Core/x/xTextureManager.o\
	$(BUILD_DIR)/src/Core/x/xTimer.o\
	$(BUILD_DIR)/src/Core/x/xTransient.o\
	$(BUILD_DIR)/asm/Core/x/xTRC.o\
	$(BUILD_DIR)/src/Core/x/xTRC.o\
	$(BUILD_DIR)/asm/Core/x/xUpdateCull.o\
	$(BUILD_DIR)/src/Core/x/xUpdateCull.o\
	$(BUILD_DIR)/asm/Core/x/xutil.o\
	$(BUILD_DIR)/src/Core/x/xutil.o\
	$(BUILD_DIR)/src/Core/x/xVec3.o\
	$(BUILD_DIR)/src/Core/x/xVolume.o\
	$(BUILD_DIR)/asm/Core/p2/iAnimSKB.o\
	$(BUILD_DIR)/src/Core/p2/iAnimSKB.o\
	$(BUILD_DIR)/asm/Core/p2/iAsync.o\
	$(BUILD_DIR)/src/Core/p2/iAsync.o\
	$(BUILD_DIR)/asm/Core/p2/iCutscene.o\
	$(BUILD_DIR)/src/Core/p2/iCutscene.o\
	$(BUILD_DIR)/asm/Core/p2/iDraw.o\
	$(BUILD_DIR)/src/Core/p2/iDraw.o\
	$(BUILD_DIR)/asm/Core/p2/iEnv.o\
	$(BUILD_DIR)/src/Core/p2/iEnv.o\
	$(BUILD_DIR)/asm/Core/p2/iFile.o\
	$(BUILD_DIR)/src/Core/p2/iFile.o\
	$(BUILD_DIR)/asm/Core/p2/iFMV.o\
	$(BUILD_DIR)/src/Core/p2/iFMV.o\
	$(BUILD_DIR)/asm/Core/p2/iFX.o\
	$(BUILD_DIR)/src/Core/p2/iFX.o\
	$(BUILD_DIR)/asm/Core/p2/iLight.o\
	$(BUILD_DIR)/src/Core/p2/iLight.o\
	$(BUILD_DIR)/src/Core/p2/iMath.o\
	$(BUILD_DIR)/asm/Core/p2/iMath3.o\
	$(BUILD_DIR)/src/Core/p2/iMath3.o\
	$(BUILD_DIR)/asm/Core/p2/iMemMgr.o\
	$(BUILD_DIR)/src/Core/p2/iMemMgr.o\
	$(BUILD_DIR)/asm/Core/p2/iModel.o\
	$(BUILD_DIR)/src/Core/p2/iModel.o\
	$(BUILD_DIR)/asm/Core/p2/iMorph.o\
	$(BUILD_DIR)/src/Core/p2/iMorph.o\
	$(BUILD_DIR)/asm/Core/p2/iPad.o\
	$(BUILD_DIR)/src/Core/p2/iPad.o\
	$(BUILD_DIR)/asm/Core/p2/isavegame.o\
	$(BUILD_DIR)/src/Core/p2/isavegame.o\
	$(BUILD_DIR)/asm/Core/p2/iScrFX.o\
	$(BUILD_DIR)/src/Core/p2/iScrFX.o\
	$(BUILD_DIR)/asm/Core/p2/iSnd.o\
	$(BUILD_DIR)/src/Core/p2/iSnd.o\
	$(BUILD_DIR)/asm/Core/p2/iSystem.o\
	$(BUILD_DIR)/src/Core/p2/iSystem.o\
	$(BUILD_DIR)/asm/Core/p2/iTime.o\
	$(BUILD_DIR)/src/Core/p2/iTime.o\
	$(BUILD_DIR)/asm/Core/p2/iTRC.o\
	$(BUILD_DIR)/src/Core/p2/iTRC.o\
	$(BUILD_DIR)/asm/Core/p2/iAnim.o\
	$(BUILD_DIR)/src/Core/p2/iAnim.o\
	$(BUILD_DIR)/asm/GAME/zZipLine.o\
	$(BUILD_DIR)/src/GAME/zZipLine.o\
	$(BUILD_DIR)/asm/GAME/zAnimCache.o\
	$(BUILD_DIR)/src/GAME/zAnimCache.o\
	$(BUILD_DIR)/asm/GAME/zAnimList.o\
	$(BUILD_DIR)/src/GAME/zAnimList.o\
	$(BUILD_DIR)/asm/GAME/zAssetTypes.o\
	$(BUILD_DIR)/src/GAME/zAssetTypes.o\
	$(BUILD_DIR)/asm/GAME/zBulletTime.o\
	$(BUILD_DIR)/src/GAME/zBulletTime.o\
	$(BUILD_DIR)/src/GAME/zCam.o\
	$(BUILD_DIR)/src/GAME/zCameraFly.o\
	$(BUILD_DIR)/src/GAME/zCameraTweak.o\
	$(BUILD_DIR)/asm/GAME/zCamFP.o\
	$(BUILD_DIR)/src/GAME/zCamFP.o\
	$(BUILD_DIR)/asm/GAME/zCamMarker.o\
	$(BUILD_DIR)/src/GAME/zCamMarker.o\
	$(BUILD_DIR)/asm/GAME/zCamPlayer.o\
	$(BUILD_DIR)/src/GAME/zCamPlayer.o\
	$(BUILD_DIR)/asm/GAME/zCamSwing.o\
	$(BUILD_DIR)/src/GAME/zCamSwing.o\
	$(BUILD_DIR)/asm/GAME/zCheat.o\
	$(BUILD_DIR)/src/GAME/zCheat.o\
	$(BUILD_DIR)/asm/GAME/zCollGeom.o\
	$(BUILD_DIR)/src/GAME/zCollGeom.o\
	$(BUILD_DIR)/asm/GAME/zCombat.o\
	$(BUILD_DIR)/src/GAME/zCombat.o\
	$(BUILD_DIR)/asm/GAME/zCombatCombo.o\
	$(BUILD_DIR)/src/GAME/zCombatCombo.o\
	$(BUILD_DIR)/asm/GAME/zCombatEffects.o\
	$(BUILD_DIR)/src/GAME/zCombatEffects.o\
	$(BUILD_DIR)/asm/GAME/zCombatLaser.o\
	$(BUILD_DIR)/src/GAME/zCombatLaser.o\
	$(BUILD_DIR)/asm/GAME/zCombatSystem.o\
	$(BUILD_DIR)/src/GAME/zCombatSystem.o\
	$(BUILD_DIR)/asm/GAME/zCommonPlayer.o\
	$(BUILD_DIR)/src/GAME/zCommonPlayer.o\
	$(BUILD_DIR)/src/GAME/zConditional.o\
	$(BUILD_DIR)/src/GAME/zConfiguration.o\
	$(BUILD_DIR)/asm/GAME/zCutsceneMgr.o\
	$(BUILD_DIR)/src/GAME/zCutsceneMgr.o\
	$(BUILD_DIR)/asm/GAME/zDashPlayer.o\
	$(BUILD_DIR)/src/GAME/zDashPlayer.o\
	$(BUILD_DIR)/asm/GAME/zDestructible.o\
	$(BUILD_DIR)/src/GAME/zDestructible.o\
	$(BUILD_DIR)/asm/GAME/zDispatcher.o\
	$(BUILD_DIR)/src/GAME/zDispatcher.o\
	$(BUILD_DIR)/asm/GAME/zDuplicator.o\
	$(BUILD_DIR)/src/GAME/zDuplicator.o\
	$(BUILD_DIR)/asm/GAME/zEGenerator.o\
	$(BUILD_DIR)/src/GAME/zEGenerator.o\
	$(BUILD_DIR)/asm/GAME/zElastiGirlPlayer.o\
	$(BUILD_DIR)/src/GAME/zElastiGirlPlayer.o\
	$(BUILD_DIR)/asm/GAME/zEnt.o\
	$(BUILD_DIR)/src/GAME/zEnt.o\
	$(BUILD_DIR)/asm/GAME/zEntButton.o\
	$(BUILD_DIR)/src/GAME/zEntButton.o\
	$(BUILD_DIR)/asm/GAME/zEntHangable.o\
	$(BUILD_DIR)/src/GAME/zEntHangable.o\
	$(BUILD_DIR)/asm/GAME/zEntSimpleObj.o\
	$(BUILD_DIR)/src/GAME/zEntSimpleObj.o\
	$(BUILD_DIR)/asm/GAME/zEntTrigger.o\
	$(BUILD_DIR)/src/GAME/zEntTrigger.o\
	$(BUILD_DIR)/src/GAME/zEnv.o\
	$(BUILD_DIR)/asm/GAME/zExplosion.o\
	$(BUILD_DIR)/src/GAME/zExplosion.o\
	$(BUILD_DIR)/asm/GAME/zFire.o\
	$(BUILD_DIR)/src/GAME/zFire.o\
	$(BUILD_DIR)/asm/GAME/zFlameEmitter.o\
	$(BUILD_DIR)/src/GAME/zFlameEmitter.o\
	$(BUILD_DIR)/src/GAME/zFMV.o\
	$(BUILD_DIR)/src/GAME/zFX.o\
	$(BUILD_DIR)/asm/GAME/zFXRibbonPool.o\
	$(BUILD_DIR)/src/GAME/zFXRibbonPool.o\
	$(BUILD_DIR)/asm/GAME/zGame.o\
	$(BUILD_DIR)/src/GAME/zGame.o\
	$(BUILD_DIR)/src/GAME/zGameExtras.o\
	$(BUILD_DIR)/src/GAME/zGameState.o\
	$(BUILD_DIR)/src/GAME/zGrapple.o\
	$(BUILD_DIR)/asm/GAME/zGrid.o\
	$(BUILD_DIR)/src/GAME/zGrid.o\
	$(BUILD_DIR)/asm/GAME/zHangable.o\
	$(BUILD_DIR)/src/GAME/zHangable.o\
	$(BUILD_DIR)/src/GAME/zHitParameters.o\
	$(BUILD_DIR)/src/GAME/zHud.o\
	$(BUILD_DIR)/asm/GAME/zHudIncredimeter.o\
	$(BUILD_DIR)/src/GAME/zHudIncredimeter.o\
	$(BUILD_DIR)/src/GAME/zHudTextureFlasher.o\
	$(BUILD_DIR)/asm/GAME/zIncrediBallPlayer.o\
	$(BUILD_DIR)/src/GAME/zIncrediBallPlayer.o\
	$(BUILD_DIR)/src/GAME/zKaboomMinigame.o\
	$(BUILD_DIR)/asm/GAME/zLaserBeam.o\
	$(BUILD_DIR)/src/GAME/zLaserBeam.o\
	$(BUILD_DIR)/asm/GAME/zLight.o\
	$(BUILD_DIR)/src/GAME/zLight.o\
	$(BUILD_DIR)/asm/GAME/zLightEffect.o\
	$(BUILD_DIR)/src/GAME/zLightEffect.o\
	$(BUILD_DIR)/asm/GAME/zLightning.o\
	$(BUILD_DIR)/src/GAME/zLightning.o\
	$(BUILD_DIR)/src/GAME/zLightWeight.o\
	$(BUILD_DIR)/asm/GAME/zLOD.o\
	$(BUILD_DIR)/src/GAME/zLOD.o\
	$(BUILD_DIR)/asm/GAME/zMain.o\
	$(BUILD_DIR)/src/GAME/zMain.o\
	$(BUILD_DIR)/asm/GAME/zMenu.o\
	$(BUILD_DIR)/src/GAME/zMenu.o\
	$(BUILD_DIR)/src/GAME/zMovePoint.o\
	$(BUILD_DIR)/asm/GAME/zMrIncrediblePlayer.o\
	$(BUILD_DIR)/src/GAME/zMrIncrediblePlayer.o\
	$(BUILD_DIR)/asm/GAME/zMusic.o\
	$(BUILD_DIR)/src/GAME/zMusic.o\
	$(BUILD_DIR)/src/GAME/zNPC.o\
	$(BUILD_DIR)/asm/GAME/zNPCArmor.o\
	$(BUILD_DIR)/src/GAME/zNPCArmor.o\
	$(BUILD_DIR)/asm/GAME/zNPCBehavior.o\
	$(BUILD_DIR)/src/GAME/zNPCBehavior.o\
	$(BUILD_DIR)/asm/GAME/zNPCBehaviorFX.o\
	$(BUILD_DIR)/src/GAME/zNPCBehaviorFX.o\
	$(BUILD_DIR)/asm/GAME/zNPCBossOmnidroid.o\
	$(BUILD_DIR)/src/GAME/zNPCBossOmnidroid.o\
	$(BUILD_DIR)/asm/GAME/zNPCCar.o\
	$(BUILD_DIR)/src/GAME/zNPCCar.o\
	$(BUILD_DIR)/asm/GAME/zNPCCombat.o\
	$(BUILD_DIR)/src/GAME/zNPCCombat.o\
	$(BUILD_DIR)/asm/GAME/zNPCFriendly.o\
	$(BUILD_DIR)/src/GAME/zNPCFriendly.o\
	$(BUILD_DIR)/asm/GAME/zNPCLobber.o\
	$(BUILD_DIR)/src/GAME/zNPCLobber.o\
	$(BUILD_DIR)/asm/GAME/zNPCMelee.o\
	$(BUILD_DIR)/src/GAME/zNPCMelee.o\
	$(BUILD_DIR)/asm/GAME/zNPCMeleeShielded.o\
	$(BUILD_DIR)/src/GAME/zNPCMeleeShielded.o\
	$(BUILD_DIR)/asm/GAME/zNPCMgr.o\
	$(BUILD_DIR)/src/GAME/zNPCMgr.o\
	$(BUILD_DIR)/asm/GAME/zNPCMine.o\
	$(BUILD_DIR)/src/GAME/zNPCMine.o\
	$(BUILD_DIR)/asm/GAME/zNPCNavigation.o\
	$(BUILD_DIR)/src/GAME/zNPCNavigation.o\
	$(BUILD_DIR)/asm/GAME/zNPCNavigationMesh.o\
	$(BUILD_DIR)/src/GAME/zNPCNavigationMesh.o\
	$(BUILD_DIR)/asm/GAME/zNPCOracle.o\
	$(BUILD_DIR)/src/GAME/zNPCOracle.o\
	$(BUILD_DIR)/asm/GAME/zNPCShooter.o\
	$(BUILD_DIR)/src/GAME/zNPCShooter.o\
	$(BUILD_DIR)/asm/GAME/zNPCTank.o\
	$(BUILD_DIR)/src/GAME/zNPCTank.o\
	$(BUILD_DIR)/asm/GAME/zNPCTurret.o\
	$(BUILD_DIR)/src/GAME/zNPCTurret.o\
	$(BUILD_DIR)/asm/GAME/zNPCTypes.o\
	$(BUILD_DIR)/src/GAME/zNPCTypes.o\
	$(BUILD_DIR)/asm/GAME/zNPCVelocipod.o\
	$(BUILD_DIR)/src/GAME/zNPCVelocipod.o\
	$(BUILD_DIR)/asm/GAME/zNPCWaterhose.o\
	$(BUILD_DIR)/src/GAME/zNPCWaterhose.o\
	$(BUILD_DIR)/asm/GAME/zPendulum.o\
	$(BUILD_DIR)/src/GAME/zPendulum.o\
	$(BUILD_DIR)/asm/GAME/zPlatform.o\
	$(BUILD_DIR)/src/GAME/zPlatform.o\
	$(BUILD_DIR)/asm/GAME/zPlayer.o\
	$(BUILD_DIR)/src/GAME/zPlayer.o\
	$(BUILD_DIR)/src/GAME/zPlayerBase.o\
	$(BUILD_DIR)/src/GAME/zPortal.o\
	$(BUILD_DIR)/src/GAME/zReference.o\
	$(BUILD_DIR)/asm/GAME/zRenderState.o\
	$(BUILD_DIR)/src/GAME/zRenderState.o\
	$(BUILD_DIR)/asm/GAME/zSaveLoad.o\
	$(BUILD_DIR)/src/GAME/zSaveLoad.o\
	$(BUILD_DIR)/asm/GAME/zScene.o\
	$(BUILD_DIR)/src/GAME/zScene.o\
	$(BUILD_DIR)/src/GAME/zScript.o\
	$(BUILD_DIR)/asm/GAME/zshell.o\
	$(BUILD_DIR)/src/GAME/zshell.o\
	$(BUILD_DIR)/asm/GAME/zShrapnel.o\
	$(BUILD_DIR)/src/GAME/zShrapnel.o\
	$(BUILD_DIR)/src/GAME/zSlideCamera.o\
	$(BUILD_DIR)/asm/GAME/zSurface.o\
	$(BUILD_DIR)/src/GAME/zSurface.o\
	$(BUILD_DIR)/src/GAME/zSymbol.o\
	$(BUILD_DIR)/asm/GAME/zTalkBox.o\
	$(BUILD_DIR)/src/GAME/zTalkBox.o\
	$(BUILD_DIR)/asm/GAME/zTaskBox.o\
	$(BUILD_DIR)/src/GAME/zTaskBox.o\
	$(BUILD_DIR)/asm/GAME/zTextBox.o\
	$(BUILD_DIR)/src/GAME/zTextBox.o\
	$(BUILD_DIR)/asm/GAME/zTrainCar.o\
	$(BUILD_DIR)/src/GAME/zTrainCar.o\
	$(BUILD_DIR)/src/GAME/zTrainPath.o\
	$(BUILD_DIR)/asm/GAME/zTransient.o\
	$(BUILD_DIR)/src/GAME/zTransient.o\
	$(BUILD_DIR)/asm/GAME/zTurret.o\
	$(BUILD_DIR)/src/GAME/zTurret.o\
	$(BUILD_DIR)/asm/GAME/zUI.o\
	$(BUILD_DIR)/src/GAME/zUI.o\
	$(BUILD_DIR)/asm/GAME/zUIBox.o\
	$(BUILD_DIR)/src/GAME/zUIBox.o\
	$(BUILD_DIR)/asm/GAME/zUIImage.o\
	$(BUILD_DIR)/src/GAME/zUIImage.o\
	$(BUILD_DIR)/asm/GAME/zUIMgr.o\
	$(BUILD_DIR)/src/GAME/zUIMgr.o\
	$(BUILD_DIR)/asm/GAME/zUIModel.o\
	$(BUILD_DIR)/src/GAME/zUIModel.o\
	$(BUILD_DIR)/asm/GAME/zUIText.o\
	$(BUILD_DIR)/src/GAME/zUIText.o\
	$(BUILD_DIR)/src/GAME/zUIUserString.o\
	$(BUILD_DIR)/asm/GAME/zVar.o\
	$(BUILD_DIR)/src/GAME/zVar.o\
	$(BUILD_DIR)/asm/GAME/zVioletPlayer.o\
	$(BUILD_DIR)/src/GAME/zVioletPlayer.o\
	$(BUILD_DIR)/src/GAME/zVolume.o\
	$(BUILD_DIR)/asm/GAME/zWaterhose.o\
	$(BUILD_DIR)/src/GAME/zWaterhose.o\
	$(BUILD_DIR)/src/GAME/zActionLine.o\
	$(BUILD_DIR)/asm/Core/x/xCollideSpherePolygon.o\
	$(BUILD_DIR)/src/Core/x/xCollideSpherePolygon.o\
	$(BUILD_DIR)/asm/GAME/zAsync.o\
	$(BUILD_DIR)/src/GAME/zAsync.o\
	$(BUILD_DIR)/asm/Core/x/xParticleBatch.o\
	$(BUILD_DIR)/src/Core/x/xParticleBatch.o\
	$(BUILD_DIR)/asm/GAME/zSmoke.o\
	$(BUILD_DIR)/src/GAME/zSmoke.o\
	$(BUILD_DIR)/asm/GAME/zSplash.o\
	$(BUILD_DIR)/src/GAME/zSplash.o\
	$(BUILD_DIR)/asm/GAME/zNPCNavigationMeshDriven.o\
	$(BUILD_DIR)/src/GAME/zNPCNavigationMeshDriven.o\
	$(BUILD_DIR)/asm/GAME/zDashCam.o\
	$(BUILD_DIR)/src/GAME/zDashCam.o\
	$(BUILD_DIR)/asm/GAME/zNPCRobotBehavior.o\
	$(BUILD_DIR)/src/GAME/zNPCRobotBehavior.o\
	$(BUILD_DIR)/asm/GAME/zIncrediSlam.o\
	$(BUILD_DIR)/src/GAME/zIncrediSlam.o\
	$(BUILD_DIR)/asm/Core/x/xScrPulseGlare.o\
	$(BUILD_DIR)/src/Core/x/xScrPulseGlare.o\
	$(BUILD_DIR)/src/GAME/zBehavior.o\
	$(BUILD_DIR)/src/GAME/zWater.o\
	$(BUILD_DIR)/asm/GAME/zIncrediBallCam.o\
	$(BUILD_DIR)/src/GAME/zIncrediBallCam.o\
	$(BUILD_DIR)/src/GAME/zTimeHandler.o\
	$(BUILD_DIR)/src/GAME/zBulletMarkAsset.o\
	$(BUILD_DIR)/asm/Core/x/xCollideSweptSphere.o\
	$(BUILD_DIR)/src/Core/x/xCollideSweptSphere.o\
	$(BUILD_DIR)/src/GAME/zNPCCommon.o\
	$(BUILD_DIR)/src/Core/x/xScreenFade.o\
	$(BUILD_DIR)/asm/GAME/zNPCWeapon.o\
	$(BUILD_DIR)/src/GAME/zNPCWeapon.o\
	$(BUILD_DIR)/asm/Core/x/xCollideSphereBox.o\
	$(BUILD_DIR)/src/Core/x/xCollideSphereBox.o\
	$(BUILD_DIR)/asm/GAME/zNPCInvisAware.o\
	$(BUILD_DIR)/src/GAME/zNPCInvisAware.o\
	$(BUILD_DIR)/asm/GAME/zNPCBotLob.o\
	$(BUILD_DIR)/src/GAME/zNPCBotLob.o\
	$(BUILD_DIR)/asm/GAME/zDashTrack.o\
	$(BUILD_DIR)/src/GAME/zDashTrack.o\
	$(BUILD_DIR)/asm/GAME/zReticle.o\
	$(BUILD_DIR)/src/GAME/zReticle.o\
	$(BUILD_DIR)/asm/GAME/zGrass.o\
	$(BUILD_DIR)/src/GAME/zGrass.o\
	$(BUILD_DIR)/asm/Core/x/xFXCameraTexture.o\
	$(BUILD_DIR)/src/Core/x/xFXCameraTexture.o\
	$(BUILD_DIR)/asm/Core/x/xFXHighDynamicRange.o\
	$(BUILD_DIR)/src/Core/x/xFXHighDynamicRange.o\
	$(BUILD_DIR)/asm/Core/x/xCollideSpherePolygonUnprocessed.o\
	$(BUILD_DIR)/src/Core/x/xCollideSpherePolygonUnprocessed.o\
	$(BUILD_DIR)/asm/GAME/zInteraction.o\
	$(BUILD_DIR)/src/GAME/zInteraction.o\
	$(BUILD_DIR)/asm/GAME/zNPCSenses.o\
	$(BUILD_DIR)/src/GAME/zNPCSenses.o\
	$(BUILD_DIR)/asm/GAME/zBomb.o\
	$(BUILD_DIR)/src/GAME/zBomb.o\
	$(BUILD_DIR)/src/GAME/zProgressScript.o\
	$(BUILD_DIR)/asm/Core/x/xHudText.o\
	$(BUILD_DIR)/src/Core/x/xHudText.o\
	$(BUILD_DIR)/asm/GAME/zFlameThrower.o\
	$(BUILD_DIR)/src/GAME/zFlameThrower.o\
	$(BUILD_DIR)/asm/GAME/zNPCFlyShooter.o\
	$(BUILD_DIR)/src/GAME/zNPCFlyShooter.o\
	$(BUILD_DIR)/asm/GAME/zRocket.o\
	$(BUILD_DIR)/src/GAME/zRocket.o\
	$(BUILD_DIR)/asm/Core/x/xHudImage.o\
	$(BUILD_DIR)/src/Core/x/xHudImage.o\
	$(BUILD_DIR)/asm/GAME/zNPCMeleeBot.o\
	$(BUILD_DIR)/src/GAME/zNPCMeleeBot.o\
	$(BUILD_DIR)/asm/GAME/zReactiveAnimation.o\
	$(BUILD_DIR)/src/GAME/zReactiveAnimation.o\
	$(BUILD_DIR)/asm/GAME/zDust.o\
	$(BUILD_DIR)/src/GAME/zDust.o\
	$(BUILD_DIR)/src/GAME/zHudDiskIndicator.o\
	$(BUILD_DIR)/src/Core/x/xProjectedTexture.o\
	$(BUILD_DIR)/asm/GAME/zSpotlight.o\
	$(BUILD_DIR)/src/GAME/zSpotlight.o\
	$(BUILD_DIR)/asm/GAME/zPickup.o\
	$(BUILD_DIR)/src/GAME/zPickup.o\
	$(BUILD_DIR)/src/GAME/zNPCGroup.o\
	$(BUILD_DIR)/asm/GAME/zThrowableSystem.o\
	$(BUILD_DIR)/src/GAME/zThrowableSystem.o\
	$(BUILD_DIR)/asm/GAME/zNPCHelibot.o\
	$(BUILD_DIR)/src/GAME/zNPCHelibot.o\
	$(BUILD_DIR)/asm/GAME/zHudDashMeter.o\
	$(BUILD_DIR)/src/GAME/zHudDashMeter.o\
	$(BUILD_DIR)/asm/GAME/zNPCBossOmnidroid10.o\
	$(BUILD_DIR)/src/GAME/zNPCBossOmnidroid10.o\
	$(BUILD_DIR)/asm/GAME/zNPCBotLeap.o\
	$(BUILD_DIR)/src/GAME/zNPCBotLeap.o\
	$(BUILD_DIR)/src/GAME/zUIController.o\
	$(BUILD_DIR)/src/Core/x/xLightVolume.o\
	$(BUILD_DIR)/asm/GAME/zUICustom.o\
	$(BUILD_DIR)/src/GAME/zUICustom.o\
	$(BUILD_DIR)/asm/GAME/zUIIncredibles.o\
	$(BUILD_DIR)/src/GAME/zUIIncredibles.o\
	$(BUILD_DIR)/asm/Core/x/xMemoryManager.o\
	$(BUILD_DIR)/src/Core/x/xMemoryManager.o\
	$(BUILD_DIR)/src/Core/x/xMemoryManagerFixed.o\
	$(BUILD_DIR)/asm/Core/x/xMemoryManagerGeneral.o\
	$(BUILD_DIR)/src/Core/x/xMemoryManagerGeneral.o\
	$(BUILD_DIR)/src/Core/p2/iException.o\
	$(BUILD_DIR)/asm/GAME/zParticleGenerator.o\
	$(BUILD_DIR)/src/GAME/zParticleGenerator.o\
	$(BUILD_DIR)/asm/GAME/zParticleLocator.o\
	$(BUILD_DIR)/src/GAME/zParticleLocator.o\
	$(BUILD_DIR)/src/GAME/zParticleSystems.o\
	$(BUILD_DIR)/asm/GAME/zParticleSystemWaterfall.o\
	$(BUILD_DIR)/src/GAME/zParticleSystemWaterfall.o\
	$(BUILD_DIR)/asm/GAME/zTurretSmoke.o\
	$(BUILD_DIR)/src/GAME/zTurretSmoke.o\
	$(BUILD_DIR)/asm/GAME/zUberLaser.o\
	$(BUILD_DIR)/src/GAME/zUberLaser.o\
	$(BUILD_DIR)/src/GAME/zLoadingScreen.o\
	$(BUILD_DIR)/asm/Core/x/xModelBlur.o\
	$(BUILD_DIR)/src/Core/x/xModelBlur.o\
	$(BUILD_DIR)/asm/Core/p2/iWater.o\
	$(BUILD_DIR)/src/Core/p2/iWater.o\
	$(BUILD_DIR)/asm/Core/p2/fxembm.o\
	$(BUILD_DIR)/src/Core/p2/fxembm.o\
	$(BUILD_DIR)/asm/Core/p2/fxmain.o\
	$(BUILD_DIR)/asm/Core/p2/texcache.o\
	$(BUILD_DIR)/src/Core/p2/texcache.o\
	$(BUILD_DIR)/asm/Core/p2/texconv.o\
	$(BUILD_DIR)/src/Core/p2/texconv.o\
	$(BUILD_DIR)/asm/Core/p2/textures.o\
	$(BUILD_DIR)/src/Core/p2/textures.o\
	$(BUILD_DIR)/asm/GAME/zEnergyStream.o\
	$(BUILD_DIR)/src/GAME/zEnergyStream.o\
	$(BUILD_DIR)/asm/GAME/zNPCSmoke.o\
	$(BUILD_DIR)/src/GAME/zNPCSmoke.o\
	$(BUILD_DIR)/asm/GAME/zNPCStreamer.o\
	$(BUILD_DIR)/src/GAME/zNPCStreamer.o\
	$(BUILD_DIR)/asm/GAME/zNPCBossBombChopper.o\
	$(BUILD_DIR)/src/GAME/zNPCBossBombChopper.o\
	$(BUILD_DIR)/src/GAME/zCameraRBand.o\
	$(BUILD_DIR)/src/GAME/zWireFrameAsset.o\
	$(BUILD_DIR)/src/GAME/zJSPExtraData.o\
	$(BUILD_DIR)/asm/GAME/zRubbleGenerator.o\
	$(BUILD_DIR)/src/GAME/zRubbleGenerator.o\
	$(BUILD_DIR)/asm/GAME/zParticleFXCommon.o\
	$(BUILD_DIR)/src/GAME/zParticleFXCommon.o\
	$(BUILD_DIR)/asm/GAME/zHudBossMeter.o\
	$(BUILD_DIR)/src/GAME/zHudBossMeter.o\
	$(BUILD_DIR)/src/Core/x/containers.o\
	$(BUILD_DIR)/src/Core/x/xFunctionGenerator.o\
	$(BUILD_DIR)/src/Core/x/xModelWarp.o\
	$(BUILD_DIR)/asm/GAME/zCombo.o\
	$(BUILD_DIR)/src/GAME/zCombo.o\
	$(BUILD_DIR)/asm/GAME/zRubbleSystem.o\
	$(BUILD_DIR)/src/GAME/zRubbleSystem.o\
	$(BUILD_DIR)/asm/GAME/zNPCPlayers.o\
	$(BUILD_DIR)/src/GAME/zNPCPlayers.o\
	$(BUILD_DIR)/src/GAME/zCineFXShared.o\
	$(BUILD_DIR)/asm/GAME/zCineFX.o\
	$(BUILD_DIR)/src/GAME/zCineFX.o\
	$(BUILD_DIR)/asm/GAME/zFrozoneIce.o\
	$(BUILD_DIR)/src/GAME/zFrozoneIce.o\
	$(BUILD_DIR)/src/Core/x/xRenderBuffer.o\
	$(BUILD_DIR)/asm/GAME/zFXFireTrail.o\
	$(BUILD_DIR)/src/GAME/zFXFireTrail.o\
	$(BUILD_DIR)/asm/GAME/zFXEnergySystem.o\
	$(BUILD_DIR)/src/GAME/zFXEnergySystem.o\
	$(BUILD_DIR)/asm/GAME/zUICustomBattleModeSelectScene.o\
	$(BUILD_DIR)/src/GAME/zUICustomBattleModeSelectScene.o\
	$(BUILD_DIR)/src/GAME/zUICustomSysMessage.o\
	$(BUILD_DIR)/asm/GAME/zUICustomBattleModeSelectPlayer.o\
	$(BUILD_DIR)/src/GAME/zUICustomBattleModeSelectPlayer.o\
	$(BUILD_DIR)/asm/Core/p2/iARAMTmp.o\
	$(BUILD_DIR)/src/Core/p2/iARAMTmp.o\
	$(BUILD_DIR)/src/GAME/zCamPreset.o\
	$(BUILD_DIR)/asm/GAME/zCineFXIN.o\
	$(BUILD_DIR)/src/GAME/zCineFXIN.o\
	$(BUILD_DIR)/asm/GAME/zSparkEmitter.o\
	$(BUILD_DIR)/src/GAME/zSparkEmitter.o\
	$(BUILD_DIR)/asm/GAME/zToss.o\
	$(BUILD_DIR)/src/GAME/zToss.o\
	$(BUILD_DIR)/asm/GAME/zHudFamilyMeter.o\
	$(BUILD_DIR)/src/GAME/zHudFamilyMeter.o\
	$(BUILD_DIR)/asm/Core/x/xIM.o\
	$(BUILD_DIR)/src/Core/x/xIM.o\
	$(BUILD_DIR)/asm/GAME/zParticleCustom.o\
	$(BUILD_DIR)/src/GAME/zParticleCustom.o\
	$(BUILD_DIR)/asm/GAME/zShrapnelEmitter.o\
	$(BUILD_DIR)/src/GAME/zShrapnelEmitter.o\
	$(BUILD_DIR)/asm/GAME/zSmashRing.o\
	$(BUILD_DIR)/src/GAME/zSmashRing.o\
	$(BUILD_DIR)/asm/GAME/zTransientModel.o\
	$(BUILD_DIR)/src/GAME/zTransientModel.o\
	$(BUILD_DIR)/asm/GAME/zIncrediBallEffect.o\
	$(BUILD_DIR)/src/GAME/zIncrediBallEffect.o\
	$(BUILD_DIR)/asm/CodeWarrior/Runtime.o\
	$(BUILD_DIR)/asm/bink/bink.o\
	$(BUILD_DIR)/asm/dolphin/dolphin.o\
	$(BUILD_DIR)/asm/fmod/fmod.o\
	$(BUILD_DIR)/asm/rwsdk/rwsdk.o\
	$(BUILD_DIR)/asm/dolphin/dolphin2.o\
	$(BUILD_DIR)/asm/CodeWarrior/MSL_C.o\
	$(BUILD_DIR)/asm/CodeWarrior/MetroTRK.o\
	$(BUILD_DIR)/asm/rwsdk/rpmatfx.o

CTORS_O_FILES :=\
	$(BUILD_DIR)/asm/ctors.o

DTORS_O_FILES :=\
	$(BUILD_DIR)/asm/dtors.o

RODATA_O_FILES :=

DATA_O_FILES :=

BSS_O_FILES :=

SDATA_O_FILES :=

SBSS_O_FILES :=

SDATA2_O_FILES :=

SBSS2_O_FILES :=

PREPROCESS_O_FILES :=\
	$(BUILD_DIR)/src/Core/x/xBase.o\
	$(BUILD_DIR)/src/Core/x/xSoundFX.o\
	$(BUILD_DIR)/src/GAME/zHud.o\
	$(BUILD_DIR)/src/GAME/zPlayerBase.o\
	$(BUILD_DIR)/src/Core/p2/iMath.o\
	$(BUILD_DIR)/src/Core/x/xGroup.o\
	$(BUILD_DIR)/src/Core/x/xFactory.o\
	$(BUILD_DIR)/src/Core/x/xEvent.o\
	$(BUILD_DIR)/src/Core/x/xVec3.o\
	$(BUILD_DIR)/src/Core/x/xSurface.o\
	$(BUILD_DIR)/src/Core/x/xBound.o\
	$(BUILD_DIR)/src/Core/x/xstransvc.o\
	$(BUILD_DIR)/src/Core/x/xHudModel.o\
	$(BUILD_DIR)/src/Core/x/xLightVolume.o\
	$(BUILD_DIR)/src/Core/x/xSkyDome.o\
	$(BUILD_DIR)/src/GAME/zCam.o\
	$(BUILD_DIR)/src/GAME/zNPC.o\
	$(BUILD_DIR)/src/Core/x/xpkrsvc.o\
	$(BUILD_DIR)/src/GAME/zGameExtras.o\
	$(BUILD_DIR)/src/GAME/zUIUserString.o
